version: "3"

services:
 server:
  build: /home/anta/udp/serveris
  command: python ./server.py
  tty: true
  ports:
    - 5000:5000

 client:
  build: /home/anta/udp/klients
  command: python ./client.py
  tty: true
   
