version: "3"

services:
 server:
  build: /home/anta/kurss/serv
  command: python ./tcpserver.py
  ports:
    - 12345:12345

 client:
  build: /home/anta/kurss/klie
  command: python ./tcpklients.py
  network_mode: host
 
