
version: "3"

services:
 server:
  build: /home/anta/telnet/telnetserver
  command: python ./server.py
  ports:
   - 1234:1234

 client:
  build: /home/anta/telnet/telnetclient
  command: python ./klients.py
  network_mode: host


